build: upd docker config

diff --git a/.docker/php/Dockerfile b/.docker/php/Dockerfile
--- a/.docker/php/Dockerfile
+++ b/.docker/php/Dockerfile
@@ -1,15 +1,25 @@
-FROM php:7.4-fpm-alpine
+FROM php:7.4-fpm-alpine3.13
 
-# utilites
-RUN set -xe \
-    && apk --no-cache add unzip gzip tar htop curl
-
-
-# setup php
+# Update repo and install some utilites
 RUN set -xe \
     && apk update \
     && apk upgrade \
+    && apk --no-cache add htop unzip gzip tar curl
+
+# Composer
+RUN set -xe \
+    && curl -L -o /composer.phar https://github.com/composer/composer/releases/download/2.0.11/composer.phar \
+    && chmod 755 /composer.phar
+ENV COMPOSER_HOME=/.composer
+COPY auth.json /.composer/
+
+# PHP
+RUN set -xe \
     && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
+
+    # Xdebug
+    && pecl install xdebug \
+    && docker-php-ext-enable xdebug \
 
     # Sodium
     && apk add --no-cache libsodium-dev \
@@ -36,20 +46,6 @@ RUN set -xe \
     && docker-php-ext-install soap \
     && docker-php-ext-enable soap \
 
-    # GD
-    && apk add --no-cache freetype libpng libwebp libjpeg-turbo freetype-dev libpng-dev libjpeg-turbo-dev libwebp-dev \
-    && docker-php-ext-configure gd \
-        --enable-gd \
-        --with-freetype \
-        --with-webp \
-        --with-jpeg \
-    && docker-php-ext-install -j$(nproc) gd \
-    && docker-php-ext-enable gd \
-
-    # Xdebug
-    && pecl install xdebug \
-    && docker-php-ext-enable xdebug \
-
     # Bcmath
     && docker-php-ext-install bcmath \
     && docker-php-ext-enable bcmath \
@@ -63,7 +59,18 @@ RUN set -xe \
     && docker-php-ext-install sockets \
     && docker-php-ext-enable sockets \
 
-    # Cleanup
+    # GD
+    && apk add --no-cache freetype libpng libwebp libjpeg-turbo freetype-dev libpng-dev libjpeg-turbo-dev libwebp-dev \
+    && docker-php-ext-configure gd \
+        --enable-gd \
+        --with-freetype \
+        --with-webp \
+        --with-jpeg \
+    && docker-php-ext-install -j$(nproc) gd \
+    && docker-php-ext-enable gd
+
+# Cleanup
+RUN set -xe \
     && apk del --no-cache .build-deps \
     && apk del --no-cache freetype-dev libpng-dev libjpeg-turbo-dev libwebp-dev \
     && apk del --no-cache icu-dev \
@@ -73,19 +80,7 @@ RUN set -xe \
     && apk del --no-cache libsodium-dev \
     && rm -rf /tmp/* /var/cache/apk/*
 
-
-# composer auth
-COPY auth.json /.composer/
-
-
-# Composer
-RUN set -xe \
-    && curl -L -o /composer.phar https://github.com/composer/composer/releases/download/2.0.11/composer.phar \
-    && chmod 755 /composer.phar
-ENV COMPOSER_HOME=/.composer
-
-
-# template of magento2
+# Template of Magento2
 RUN set -xe \
     && cd / \
     && php -d memory_limit=-1 /composer.phar create-project --repository=https://repo.magento.com/ magento/project-community-edition:2.4.* mg24 \
